---
# Installs Eclipse plugins

- name: Install FindBugs plugin
  command: >
    {{ eclipse_binary }}
    -noSplash
    -application org.eclipse.equinox.p2.director
    -repository http://findbugs.cs.umd.edu/eclipse
    -repository http://download.eclipse.org/releases/{{ eclipse_version }}
    -installIU edu.umd.cs.findbugs.plugin.eclipse.feature.group

- name: Install EclEmma plugin
  command: >
    {{ eclipse_binary }}
    -noSplash
    -application org.eclipse.equinox.p2.director
    -repository http://update.eclemma.org/
    -repository http://download.eclipse.org/releases/{{ eclipse_version }}
    -installIU com.mountainminds.eclemma.feature.feature.group

- name: Install Metrics plugin
  command: >
    {{ eclipse_binary }}
    -noSplash
    -application org.eclipse.equinox.p2.director
    -repository http://metrics.sourceforge.net/update
    -repository http://download.eclipse.org/releases/{{ eclipse_version }}
    -installIU net.sourceforge.metrics.feature.group

- name: Install J2EE
  command: >
    {{ eclipse_binary }}
    -noSplash
    -application org.eclipse.equinox.p2.director
    -repository http://download.eclipse.org/releases/{{ eclipse_version }}
    -installIUs
    org.eclipse.jst.enterprise_ui.feature.feature.group,\
    org.eclipse.jst.web_ui.feature.feature.group,\
    org.eclipse.jst.server_adapters.feature.feature.group,\
    org.eclipse.jst.server_adapters.ext.feature.feature.group,\
    org.eclipse.jst.server_ui.feature.feature.group,\
    org.eclipse.wst.xml_ui.feature.feature.group,\
    org.eclipse.wst.jsdt.feature.feature.group,\
    org.eclipse.m2e.feature.feature.group,\
    org.eclipse.m2e.wtp.feature.feature.group,\
    org.eclipse.mylyn_feature.feature.group,\
    org.eclipse.rse.feature.group
